/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.JogadorVO;
import servicos.JogadorServicos;
import servicos.ServicosFactory;

/**
 *
 * @author João Victor Candido, Gabriel Fraga
 * @since 07/05/2019
 * @version 1.0 Groot
 */
public class GUICadJogador extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadJogador
     */
    public GUICadJogador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jlValorPasse = new javax.swing.JLabel();
        jlPosicao = new javax.swing.JLabel();
        jlClubeOrigem = new javax.swing.JLabel();
        jlClubeAtual = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtIdade = new javax.swing.JTextField();
        jtValorPasse = new javax.swing.JTextField();
        jtPosicao = new javax.swing.JTextField();
        jtClubeOrigem = new javax.swing.JTextField();
        jtClubeAtual = new javax.swing.JTextField();
        jtSalario = new javax.swing.JTextField();
        Acoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        Dados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlIdade.setText("Idade");

        jlValorPasse.setText("Valor do passe");

        jlPosicao.setText("Posição");

        jlClubeOrigem.setText("Clube de origem");

        jlClubeAtual.setText("Clube atual");

        jlSalario.setText("Salário");

        Dados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlValorPasse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlPosicao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlClubeOrigem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlClubeAtual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlSalario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtValorPasse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtPosicao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtClubeOrigem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtClubeAtual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtSalario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DadosLayout = new javax.swing.GroupLayout(Dados);
        Dados.setLayout(DadosLayout);
        DadosLayout.setHorizontalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSalario)
                    .addComponent(jlIdade)
                    .addComponent(jlNome)
                    .addComponent(jlValorPasse)
                    .addComponent(jlPosicao)
                    .addComponent(jlClubeOrigem)
                    .addComponent(jlClubeAtual))
                .addGap(41, 41, 41)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtNome)
                    .addComponent(jtIdade)
                    .addComponent(jtValorPasse)
                    .addComponent(jtPosicao)
                    .addComponent(jtClubeOrigem)
                    .addComponent(jtClubeAtual)
                    .addComponent(jtSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        DadosLayout.setVerticalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdade)
                    .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorPasse)
                    .addComponent(jtValorPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPosicao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtClubeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlClubeOrigem))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlClubeAtual)
                    .addComponent(jtClubeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario)
                    .addComponent(jtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Acoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        Acoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Acoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AcoesLayout = new javax.swing.GroupLayout(Acoes);
        Acoes.setLayout(AcoesLayout);
        AcoesLayout.setHorizontalGroup(
            AcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcoesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AcoesLayout.setVerticalGroup(
            AcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcoesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(AcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel1.setText("Cadastro de Jogadores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Acoes))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Acoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cadastrar() {
        
        try {
            if(jtNome.getText().isEmpty()) throw new NumberFormatException("Nome inválido!");
            if(jtIdade.getText().isEmpty()) throw new NumberFormatException("Idade inválida!");
            if(jtValorPasse.getText().isEmpty()) throw new NumberFormatException("Campo inválido!");
            if(jtPosicao.getText().isEmpty()) throw new NumberFormatException("Posição inválida!");
            if(jtClubeOrigem.getText().isEmpty()) throw new NumberFormatException("Campo inválido!");
            if(jtClubeAtual.getText().isEmpty()) throw new NumberFormatException("Campo inválido!");
            if(jtSalario.getText().isEmpty()) throw new NumberFormatException("Campo inválido!");
            
            JogadorVO jVO = new JogadorVO();
            
            jVO.setNome(jtNome.getText());
            jVO.setIdade(Integer.parseInt(jtIdade.getText()));
            jVO.setValorPasse(Double.parseDouble(jtValorPasse.getText()));
            jVO.setPosicao(jtPosicao.getText());
            jVO.setClubeOrigem(jtClubeOrigem.getText());
            jVO.setClubeAtual(jtClubeAtual.getText());
            jVO.setSalario(Double.parseDouble(jtSalario.getText()));
            
            JogadorServicos js = ServicosFactory.getJogadorServicos();
            js.cadastrarJogador(jVO);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Jogador cadastrado com sucesso!");

             JOptionPane.showMessageDialog(
                    this, 
                    "Relatório:\n"+jVO.toString(),
                    "Relatório",
                    JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
        
    }// fecha cadastrar
    
    private void limpar() {
        jtNome.setText("");
        jtIdade.setText("");
        jtValorPasse.setText("");
        jtPosicao.setText("");
        jtClubeOrigem.setText("");
        jtClubeAtual.setText("");
        jtSalario.setText("");
        
        jtNome.grabFocus();
    }// fecha limpar
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbLimparKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Acoes;
    private javax.swing.JLayeredPane Dados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlClubeAtual;
    private javax.swing.JLabel jlClubeOrigem;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPosicao;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JLabel jlValorPasse;
    private javax.swing.JTextField jtClubeAtual;
    private javax.swing.JTextField jtClubeOrigem;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPosicao;
    private javax.swing.JTextField jtSalario;
    private javax.swing.JTextField jtValorPasse;
    // End of variables declaration//GEN-END:variables
}
