/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.ClubeVO;
import servicos.ClubeServicos;
import servicos.ServicosFactory;

/**
 *
 * @author João Victor Candido, Gabriel Fraga
 * @since 07/05/2019
 * @version 1.0 Groot
 */
public class GUICadClube extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadClube
     */
    public GUICadClube() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlLiga = new javax.swing.JLabel();
        jlRanking = new javax.swing.JLabel();
        jlOrcamento = new javax.swing.JLabel();
        jlTecnico = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtLiga = new javax.swing.JTextField();
        jtRanking = new javax.swing.JTextField();
        jtOrcamento = new javax.swing.JTextField();
        jtTecnico = new javax.swing.JTextField();
        Acoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        Dados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlLiga.setText("Liga");

        jlRanking.setText("Ranking");

        jlOrcamento.setText("Orçamento");

        jlTecnico.setText("Técnico");

        Dados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlLiga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlRanking, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlOrcamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jlTecnico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtLiga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtRanking, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtOrcamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dados.setLayer(jtTecnico, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DadosLayout = new javax.swing.GroupLayout(Dados);
        Dados.setLayout(DadosLayout);
        DadosLayout.setHorizontalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome)
                    .addComponent(jlLiga)
                    .addComponent(jlRanking)
                    .addComponent(jlOrcamento)
                    .addComponent(jlTecnico))
                .addGap(87, 87, 87)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(jtLiga)
                        .addComponent(jtRanking)
                        .addComponent(jtOrcamento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DadosLayout.setVerticalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLiga)
                    .addComponent(jtLiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlRanking)
                    .addComponent(jtRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlOrcamento)
                    .addComponent(jtOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTecnico)
                    .addComponent(jtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        Acoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        Acoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Acoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AcoesLayout = new javax.swing.GroupLayout(Acoes);
        Acoes.setLayout(AcoesLayout);
        AcoesLayout.setHorizontalGroup(
            AcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcoesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        AcoesLayout.setVerticalGroup(
            AcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcoesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(AcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setText("Cadastro de Clubes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Acoes)
                    .addComponent(Dados))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(Dados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Acoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cadastrar() {
        
        try {
            if(jtNome.getText().isEmpty()) throw new NumberFormatException("Nome inválido!");
            if(jtLiga.getText().isEmpty()) throw new NumberFormatException("Liga não existente!");
            if(jtRanking.getText().isEmpty()) throw new NumberFormatException("Campo inválido!");
            if(jtOrcamento.getText().isEmpty()) throw new NumberFormatException("Campo inválido!");
            if(jtTecnico.getText().isEmpty()) throw new NumberFormatException("Campo inválido!");
            
            ClubeVO cVO = new ClubeVO();
            
            cVO.setNomeClube(jtNome.getText());
            cVO.setLigaClube(jtLiga.getText());
            cVO.setRanking(Integer.parseInt(jtRanking.getText()));
            cVO.setOrcamento(Double.parseDouble(jtOrcamento.getText()));
            cVO.setTecnico(jtTecnico.getText());
            
            ClubeServicos cs = ServicosFactory.getClubeServicos();
            cs.cadastrarClube(cVO);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Clube cadastrado com sucesso!");
            
            JOptionPane.showMessageDialog(
                    this, 
                    "Relatório:\n"+cVO.toString(),
                    "Relatório",
                    JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }// fecha catch
        
    }// fecha cadastrar
    
    private void limpar() {
        jtNome.setText("");
        jtLiga.setText("");
        jtRanking.setText("");
        jtOrcamento.setText("");
        jtTecnico.setText("");

        jtNome.grabFocus();
    }// fecha limpar
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }//fecha if
    }//GEN-LAST:event_jbLimparKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Acoes;
    private javax.swing.JLayeredPane Dados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlLiga;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlOrcamento;
    private javax.swing.JLabel jlRanking;
    private javax.swing.JLabel jlTecnico;
    private javax.swing.JTextField jtLiga;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtOrcamento;
    private javax.swing.JTextField jtRanking;
    private javax.swing.JTextField jtTecnico;
    // End of variables declaration//GEN-END:variables
}
