/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ClubeVO;
import servicos.ClubeServicos;
import servicos.ServicosFactory;

/**
 *
 * @author João Victor Candido, Gabriel Fraga
 * @since 08/05/2019
 * @version 1.0 Groot
 */
public class GUIManutencaoClube extends javax.swing.JInternalFrame {
         DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Nome", "Liga", "Ranking", "Orcçamento", "Técnico"});

    /**
     * Creates new form GUIManutencaoClube
     */
    public GUIManutencaoClube() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableClube = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jbBuscar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jlPesquisa = new javax.swing.JLabel();
        jtPesquisa = new javax.swing.JTextField();
        jcbFiltro = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jtableClube.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtableClube.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtableClube);

        jLabel1.setText("Manutenção Clube");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLimpar)
                    .addComponent(jbAlterar))
                .addContainerGap())
        );

        jlPesquisa.setText("Pesquisa");

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Liga", "Ranking", "Orçamento", "Técnico" }));
        jcbFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbFiltroItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPesquisa)
                                .addGap(36, 36, 36)
                                .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(64, 64, 64)
                        .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisa)
                    .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        preencherTabela();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletarTabela();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesquisaKeyReleased

    private void jcbFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFiltroItemStateChanged
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jcbFiltroItemStateChanged

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        alterarAtravesTabela();
    }//GEN-LAST:event_jbAlterarActionPerformed

        
    private void preencherTabela() {
        try {
            ArrayList<ClubeVO> clubes = new ArrayList<>();
            ClubeServicos cs = servicos.ServicosFactory.getClubeServicos();
            clubes = cs.buscarClube();

//            limparTabela();
            
            for (int i = 0; i < clubes.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(clubes.get(i).getIdClube()),
                    clubes.get(i).getNomeClube(),
                    clubes.get(i).getLigaClube(),
                    String.valueOf(clubes.get(i).getRanking()),
                    String.valueOf(clubes.get(i).getOrcamento()),
                    clubes.get(i).getTecnico(),
                });
            }
            jtableClube.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        }
    }// fecha método
    
    private void deletarTabela() {
        try {
            int linha = jtableClube.getSelectedRow();
            if(linha == -1) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Selecione uma linha para excluir!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }//fecha if
            
            String id = jtableClube.getValueAt(linha, 0).toString();
            
            ClubeServicos cs = ServicosFactory.getClubeServicos();
            cs.deletarClube(Long.parseLong(id));
            
            JOptionPane.showMessageDialog(this, 
                    "Clube excluido com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Erro!"+e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//fecha método deletar
    
    private void limparTabela() {
        dtm.setNumRows(0);
    }
    
    private void alterarAtravesTabela() {
        try {
            int linha = jtableClube.getSelectedRow();
            String id = jtableClube.getValueAt(linha, 0).toString();
            String nome = jtableClube.getValueAt(linha, 1).toString();
            String liga = jtableClube.getValueAt(linha, 2).toString();
            String ranking = jtableClube.getValueAt(linha, 3).toString();
            String orcamento = jtableClube.getValueAt(linha, 4).toString();
            String tecnico = jtableClube.getValueAt(linha, 5).toString();

            ClubeVO c = new ClubeVO();
            c.setIdClube(Long.parseLong(id));
            c.setNomeClube(nome);
            c.setLigaClube(liga);
            c.setRanking(Integer.parseInt(ranking));
            c.setOrcamento(Double.parseDouble(orcamento));
            c.setTecnico(tecnico);

            ClubeServicos cs = ServicosFactory.getClubeServicos();
            cs.alterarClube(c);

            JOptionPane.showMessageDialog(this,
                    "Clube alterado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro!" + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }// fecha método

   private void filtrar() {
        try {
            if(jtPesquisa.getText().isEmpty()) {
                limparTabela();
                preencherTabela();
                return;
            }
            String pesquisa = jtPesquisa.getText();
            String filtro = jcbFiltro.getSelectedItem().toString();
            ClubeServicos cs = ServicosFactory.getClubeServicos();
            ArrayList<ClubeVO> clu = cs.filtrar(pesquisa, filtro);
            
            for(int i=0 ; i<clu.size() ; i++) {
                dtm.addRow(new String[]{
                    String.valueOf(clu.get(i).getIdClube()),
                    clu.get(i).getNomeClube(),
                    String.valueOf(clu.get(i).getLigaClube()),
                    String.valueOf(clu.get(i).getRanking()),
                    String.valueOf(clu.get(i).getOrcamento()),
                    String.valueOf(clu.get(i).getTecnico()),
                });
            }
            jtableClube.setModel(dtm);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(
                    this, 
                    "Erro!"+e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//fecha metodo
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox<String> jcbFiltro;
    private javax.swing.JLabel jlPesquisa;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTable jtableClube;
    // End of variables declaration//GEN-END:variables
}
