/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author João Victor Candido, Gabriel Fraga
 * @since 07/05/2019
 * @version 1.0 Groot
 */
public class MenuPrincipal extends javax.swing.JFrame implements InternalFrameListener{
    
     private boolean flagCadJogador = false;
     private boolean flagCadClube = false;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    private void abrirCadJogador(){
        if(!flagCadJogador) {
            GUICadJogador gcj = new GUICadJogador();
            jAreaDeTrabalho.add(gcj);
            gcj.setVisible(true);
            flagCadJogador = true;
            gcj.addInternalFrameListener(this);
        }// fecha if
    }//fecha método
    
    private void abrirCadClube(){
       if(!flagCadClube) {
        GUICadClube gcc = new GUICadClube();
        jAreaDeTrabalho.add(gcc);
        gcc.setVisible(true);
        flagCadClube = true;
        gcc.addInternalFrameListener(this);
       }// fecha if
    }//fecha método
    
    private void abrirManJogador() {
        GUIManutencaoJogador gms = new GUIManutencaoJogador();
        jAreaDeTrabalho.add(gms);
        gms.setVisible(true);
    }// fecha método
    
    private void abrirManClube() {
        GUIManutencaoClube gms = new GUIManutencaoClube();
        jAreaDeTrabalho.add(gms);
        gms.setVisible(true);
    }// fecha método
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmCadJogador = new javax.swing.JMenuItem();
        jmCadClube = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiJogador = new javax.swing.JMenuItem();
        jmiClube = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jAreaDeTrabalho);
        jAreaDeTrabalho.setLayout(jAreaDeTrabalhoLayout);
        jAreaDeTrabalhoLayout.setHorizontalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jAreaDeTrabalhoLayout.setVerticalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jmCadastro.setText("Cadastro");
        jmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroActionPerformed(evt);
            }
        });

        jmCadJogador.setText("Jogador");
        jmCadJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadJogadorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadJogador);

        jmCadClube.setText("Clube");
        jmCadClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadClubeActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadClube);

        jMenuBar1.add(jmCadastro);

        jMenu2.setText("Manutenção");

        jmiJogador.setText("Jogador");
        jmiJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJogadorActionPerformed(evt);
            }
        });
        jMenu2.add(jmiJogador);

        jmiClube.setText("Clube");
        jmiClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClubeActionPerformed(evt);
            }
        });
        jMenu2.add(jmiClube);

        jMenuBar1.add(jMenu2);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaDeTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadJogadorActionPerformed
       abrirCadJogador();
    }//GEN-LAST:event_jmCadJogadorActionPerformed

    private void jmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroActionPerformed
        
    }//GEN-LAST:event_jmCadastroActionPerformed

    private void jmCadClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadClubeActionPerformed
        abrirCadClube();
    }//GEN-LAST:event_jmCadClubeActionPerformed

    private void jmiJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJogadorActionPerformed
        abrirManJogador();
    }//GEN-LAST:event_jmiJogadorActionPerformed

    private void jmiClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClubeActionPerformed
        abrirManClube();
    }//GEN-LAST:event_jmiClubeActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        int op = JOptionPane.showConfirmDialog(this,
                "Você deseja realmente sair!?");

        if (op == 0) {
            System.exit(0);
        }//fecha if
    }//GEN-LAST:event_jmSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaDeTrabalho;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmCadClube;
    private javax.swing.JMenuItem jmCadJogador;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiClube;
    private javax.swing.JMenuItem jmiJogador;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        if(ife.getInternalFrame() instanceof GUICadJogador) {
            flagCadJogador = false;
        }// fecha if
        
        if(ife.getInternalFrame() instanceof GUICadClube) {
            flagCadClube = false;
        }// fecha if
        
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
    }
}
